"""Initial

Revision ID: ff298875423e
Revises: ea8decc5e142
Create Date: 2025-06-27 20:01:32.502370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff298875423e'
down_revision = 'ea8decc5e142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('workout_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('exercises_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'])
        batch_op.drop_column('muscle_group')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('muscle_group', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('exercises_name_key', ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('workout_id')
        batch_op.drop_column('weight')
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')

    op.create_table('workout_exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='workout_exercises_exercise_id_fkey'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='workout_exercises_workout_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workout_exercises_pkey')
    )
    # ### end Alembic commands ###
